### ISSUE TITLE
renaming "Procrastinators" organization name

### ISSUE THREAD

**Issue by eralpkaraduman** [Procrastinators/babybook#1]
Hi,

We'd like to register organization name "procrasatinators", but you had already registered it.
You seem to have no significant activity. Can you please rename it so we can claim it, if you have no plans to  use it in the future?

Thank you.

**Comment by codingfrenzy** [comment]
Hi.. 
I'm sorry.
Even though we have not been active, we have plans to pick it up again.
Hope you find a better name!

**Comment by eralpkaraduman** [comment]
Thank you for responding
